apiVersion: v1
kind: Service
metadata:
  name: gateway-api
  labels:
    app: gateway-api
spec:
  selector:
    app: gateway-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
